
import gspread
from google.oauth2.service_account import Credentials
import pandas as pd
import os

# Google Sheets Setup
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

SERVICE_ACCOUNT_FILE = 'service_account.json'

def connect_to_sheet(sheet_url_or_name):
    """
    Connects to Google Sheet using service account
    """
    if not os.path.exists(SERVICE_ACCOUNT_FILE):
        raise FileNotFoundError(f"Service account file not found: {SERVICE_ACCOUNT_FILE}")

    creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
    gc = gspread.authorize(creds)

    try:
        # Try opening by URL first (safer)
        if "docs.google.com" in sheet_url_or_name:
            sheet = gc.open_by_url(sheet_url_or_name)
        else:
            sheet = gc.open(sheet_url_or_name)
        return sheet.sheet1 # Assuming data is in first sheet
    except Exception as e:
        print(f"Error connecting to sheet: {e}")
        return None

def fetch_pending_posts(sheet_url):
    """
    Fetches rows where:
    - Generated Content is NOT empty
    - Status is 'Done' (Generated by AI)
    - (Optionally) Update status to 'Scheduled' after fetching to prevent double posting
    """
    worksheet = connect_to_sheet(sheet_url)
    if not worksheet:
        return []

    # Get all values
    rows = worksheet.get_all_values()
    if not rows:
        return []

    headers = rows[0]
    data = rows[1:]

    # Convert to standard list of dicts
    # Headers: Topic, Type, Goal, Generated Content, Image Prompt, Status
    # Indices: 0,     1,    2,    3,                 4,            5
    
    pending_posts = []
    
    # Identify column indices manually to be safe
    try:
        idx_content = headers.index("Generated Content")
        idx_status = headers.index("Status")
        idx_type = headers.index("Type (タイプ)")
        idx_topic = headers.index("Topic (テーマ)")
        idx_prompt = headers.index("Image Prompt")
    except ValueError:
        print("Error: Sheet headers do not match expected format.")
        return []

    for i, row in enumerate(data):
        # Safety check for row length
        if len(row) <= max(idx_content, idx_status): 
            continue
            
        content = row[idx_content]
        status = row[idx_status]
        
        # Logic: Fetch if content exists and status is 'Done' (meaning AI wrote it, but not yet posted)
        # You might want a specific status like 'Ready'
        if content and status == "Done":
            post_data = {
                "row_index": i + 2, # 1-based index, skipping header
                "type": row[idx_type] if len(row) > idx_type else "Feed",
                "caption": content,
                "image_prompt": row[idx_prompt] if len(row) > idx_prompt else "",
                "topic": row[idx_topic] if len(row) > idx_topic else ""
            }
            pending_posts.append(post_data)

    print(f"Found {len(pending_posts)} pending posts.")
    return pending_posts

def update_post_status(sheet_url, row_index, new_status="Scheduled"):
    """
    Updates the status of a specific row (e.g., to 'Posted' or 'Scheduled')
    """
    worksheet = connect_to_sheet(sheet_url)
    if worksheet:
        # Status is in column F (6th column) usually
        # But let's find it dynamically or assume standard v3.2 format
        worksheet.update_cell(row_index, 6, new_status)
        print(f"Row {row_index} status updated to {new_status}")

if __name__ == "__main__":
    # Test execution
    print("--- Testing Sheets Integration ---")
    url = input("Enter Google Sheet URL: ")
    posts = fetch_pending_posts(url)
    for p in posts:
        print(f"Pending: {p['type']} - {p['topic']}")
