from pptx import Presentation
from pptx.util import Inches, Pt
import re
import requests
from io import BytesIO

class PPTXExporter:
    def __init__(self):
        self.prs = Presentation()

    def export(self, markdown_text, output_file="manual_export.pptx"):
        """
        Parses Markdown text and creates a PPTX.
        Rules:
        - # (H1) -> Title Slide (Section Divider)
        - ## (H2) -> Content Slide (Title + Bullets)
        - ### (H3) or - -> Bullet Points
        - [Image] -> Puts image on right side if possible
        - Overflow: Auto-splits slides if > 7 lines
        """
        
        lines = markdown_text.split('\n')
        current_slide = None
        current_tf = None
        current_title = ""
        line_count = 0
        MAX_LINES = 7
        
        # Create Title Slide (Cover)
        title_slide_layout = self.prs.slide_layouts[0]
        cover = self.prs.slides.add_slide(title_slide_layout)
        cover.shapes.title.text = "Business Manual"
        cover.placeholders[1].text = "Generated by AI Manual Architect"

        for line in lines:
            line = line.rstrip()
            if not line: continue

            # --- H1: Section Title ---
            if line.startswith('# '):
                text = line.replace('# ', '').strip()
                layout = self.prs.slide_layouts[0] # Title Slide
                slide = self.prs.slides.add_slide(layout)
                slide.shapes.title.text = text
                current_slide = slide
                current_tf = None
                current_title = text
                line_count = 0

            # --- H2: New Content Slide ---
            elif line.startswith('## '):
                text = line.replace('## ', '').strip()
                current_title = text
                current_slide, current_tf = self._add_content_slide(text)
                line_count = 0

            # --- Bullets ---
            elif line.strip().startswith('- ') or line.strip().startswith('* '):
                # Check for overflow
                if line_count >= MAX_LINES:
                    current_slide, current_tf = self._add_content_slide(f"{current_title} (Cont.)")
                    line_count = 0
                
                indent = len(line) - len(line.lstrip())
                level = 0 if indent < 2 else 1
                
                text = line.strip()[2:].strip()
                if current_tf:
                    p = current_tf.add_paragraph()
                    p.text = text
                    p.level = level
                    # p.font.size = Pt(18) # specific font size if needed
                    line_count += 1
            
            # --- Images ---
            elif line.strip().startswith('!['):
                # Extract URL: ![alt](url)
                match = re.search(r'\((.*?)\)', line)
                if match and current_slide:
                    img_url = match.group(1)
                    self._add_image_to_slide(current_slide, img_url)

            # --- Plain Text (Append) ---
            else:
                 if current_tf and not line.startswith('<'):
                    if line_count >= MAX_LINES:
                        current_slide, current_tf = self._add_content_slide(f"{current_title} (Cont.)")
                        line_count = 0

                    p = current_tf.add_paragraph()
                    p.text = line
                    p.level = 0
                    line_count += 1
        
        self.prs.save(output_file)
        return output_file

    def _add_content_slide(self, title):
        layout = self.prs.slide_layouts[1] # Title + Content
        slide = self.prs.slides.add_slide(layout)
        slide.shapes.title.text = title
        tf = slide.shapes.placeholders[1].text_frame
        tf.clear()
        return slide, tf

    def _add_image_to_slide(self, slide, url):
        try:
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                image_stream = BytesIO(response.content)
                # Position: Right side (approx)
                # Slide width is usually 10 inches.
                left = Inches(6.5)
                top = Inches(2)
                width = Inches(3)
                slide.shapes.add_picture(image_stream, left, top, width=width)
        except Exception as e:
            print(f"Image Add Error: {e}")
